services:

  frontend:
    container_name: microservices_frontend
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    network_mode: host
    stdin_open: true
    
    command: yarn start